CREATE TABLE [dbo].[Table]
(
	[Game] INT NOT NULL PRIMARY KEY,
	[Year] INT NOT NULL, 
    [Week] INT NOT NULL, 
    [ConfGame] CHAR(10) NOT NULL, 
    [Home] CHAR(10) NOT NULL, 
    [Away] CHAR(10) NOT NULL, 
    [Winning Team] CHAR(10) NOT NULL, 
    [Home End Game Pts] INT NOT NULL, 
    [Away End Game Pts] INT NOT NULL, 
    [Home Passing Yards] INT NOT NULL, 
    [Away Passing Yards] INT NOT NULL, 
    [Home Turnovers] INT NOT NULL, 
    [Away Turnovers] INT NOT NULL, 
    [HomeForcedFum] INT NOT NULL,  
    [HomeInt] INT NOT NULL, 
    [AwayForcedFum] INT NOT NULL, 
    [TotalRushingYards] INT NOT NULL, 
    [HomeRushingYards] INT NOT NULL, 
    [AwayRushingYards] INT NOT NULL, 
    [TotalYardsLost] INT NOT NULL, 
    [HomeTeamYardsLost] INT NOT NULL, 
    [AwayTeamYardsLost] INT NOT NULL, 
    [TotalTDs] INT NOT NULL, 
    [HomeTeamTDs] INT NOT NULL, 
    [AwayTeamTDs] INT NOT NULL, 
    [TotalRushingTDs] INT NOT NULL, 
    [HomeRushingTD] INT NOT NULL, 
    [AwayRushingTD] IMAGE NOT NULL, 
    [HomeTeamInjuries] INT NOT NULL, 
    [AwayTeamInjuries] INT NOT NULL, 
    [HomeTeamBall Possession] TIME NOT NULL, 
    [AwayTeamBall Possession] TIME NOT NULL, 
    [GameLength] TIME NOT NULL
)
