CREATE TABLE [dbo].Game
(
	[Game] INT NOT NULL PRIMARY KEY IDENTITY,
	[Year] INT DEFAULT 0 NOT NULL, 
    [Week] INT DEFAULT 0 NOT NULL, 
    [ConfGame] CHAR(10) NOT NULL DEFAULT 'yes', 
    [Home] CHAR(10) NOT NULL, 
    [Away] CHAR(10) NOT NULL, 
    [Winning Team] CHAR(10) NOT NULL, 
    [Home End Game Pts] INT DEFAULT 0 NOT NULL, 
    [Away End Game Pts] INT DEFAULT 0 NOT NULL,
    [Home Passing Yards] INT DEFAULT 0 NOT NULL,
    [Away Passing Yards] INT DEFAULT 0 NOT NULL,
    [Home Turnovers] INT DEFAULT 0 NOT NULL,
    [Away Turnovers] INT DEFAULT 0 NOT NULL, 
    [HomeForcedFum] INT DEFAULT 0 NOT NULL,  
    [HomeInt] INT DEFAULT 0 NOT NULL, 
    [AwayForcedFum] INT DEFAULT 0 NOT NULL, 
    [TotalRushingYards] INT DEFAULT 0 NOT NULL, 
    [HomeRushingYards] INT DEFAULT 0 NOT NULL, 
    [AwayRushingYards] INT DEFAULT 0 NOT NULL, 
    [TotalYardsLost] INT DEFAULT 0 NOT NULL, 
    [HomeTeamYardsLost] INT DEFAULT 0 NOT NULL, 
    [AwayTeamYardsLost] INT DEFAULT 0 NOT NULL, 
    [TotalTDs] INT DEFAULT 0 NOT NULL, 
    [HomeTeamTDs] INT DEFAULT 0 NOT NULL, 
    [AwayTeamTDs] INT DEFAULT 0 NOT NULL, 
    [TotalRushingTDs] INT DEFAULT 0 NOT NULL, 
    [HomeRushingTD] INT DEFAULT 0 NOT NULL, 
    [AwayRushingTD] INT DEFAULT 0 NOT NULL, 
    [HomeTeamInjuries] INT DEFAULT 0 NOT NULL, 
    [AwayTeamInjuries] INT DEFAULT 0 NOT NULL, 
    [HomeTeamBall Possession] TIME DEFAULT '0:00' NOT NULL, 
    [AwayTeamBall Possession] TIME DEFAULT '0:00' NOT NULL, 
    [GameLength] TIME DEFAULT '0:00' NOT NULL
)
