CREATE TABLE [dbo].[Table]
(
	[Id] INT NOT NULL PRIMARY KEY, 
    [First Name] NCHAR(10) NULL, 
    [Last Name] NCHAR(10) NULL, 
    [Team] NCHAR(10) NULL, 
    [Game Played] INT NULL DEFAULT 0, 
    [Completion] INT NULL DEFAULT 0, 
    [Attempts] INT NULL DEFAULT 0, 
    [Passing Yards] INT NULL DEFAULT 0, 
    [Passing Touchdowns] INT NULL 
    CONSTRAINT [PK_Table] PRIMARY KEY ([Id]) DEFAULT 0, 
    [Interception Thrown] INT NULL DEFAULT 0, 
    [Fumbles] INT NULL DEFAULT 0, 
    [Rushing Attempts] INT NULL DEFAULT 0, 
    [Rushing Yards] INT NULL DEFAULT 0, 
    [Rushing Touchdowns] INT NULL DEFAULT 0, 
    [Fumbles Lost] INT NULL DEFAULT 0, 
    [Receptions] INT NULL DEFAULT 0, 
    [Receiving Yards] INT NULL DEFAULT 0, 
    [Receiving Touchdowns] INT NULL DEFAULT 0, 
    [Return Touchdowns] INT NULL DEFAULT 0, 
    [2PT] INT NULL DEFAULT 0, 
    [PAT] INT NULL DEFAULT 0, 
    [FG] INT NULL DEFAULT 0, 
    [Punts] INT NULL DEFAULT 0, 
    [Longest Punts] INT NULL DEFAULT 0, 
    [Total Punting Yards] INT NULL DEFAULT 0, 
    CONSTRAINT [PK_Table] PRIMARY KEY ([Id]), 
    CONSTRAINT [Team] FOREIGN KEY ([Column]) REFERENCES [ToTable]([ToTableColumn]), 
    CONSTRAINT [PK_Table] PRIMARY KEY ([Id]), 
    CONSTRAINT [FK_Table_ToTable] FOREIGN KEY ([Column]) REFERENCES [ToTable]([ToTableColumn]), 
    CONSTRAINT [FK_Table_ToTable] FOREIGN KEY ([Column]) REFERENCES [ToTable]([ToTableColumn]), 
    CONSTRAINT [PK_Table] PRIMARY KEY ([Id])
)
